return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.6.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 30,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 6,
  nextobjectid = 289,
  properties = {},
  tilesets = {
    {
      name = "tileset",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 2,
      margin = 1,
      columns = 7,
      image = "../sprites/tileset.png",
      imagewidth = 255,
      imageheight = 289,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 56,
      tiles = {
        {
          id = 7,
          type = "greyDoor"
        },
        {
          id = 10,
          type = "speeder"
        },
        {
          id = 14,
          type = "redDoor"
        },
        {
          id = 21,
          type = "blueDoor"
        },
        {
          id = 28,
          type = "coin"
        },
        {
          id = 31,
          type = "life"
        },
        {
          id = 32,
          type = "greyButton"
        },
        {
          id = 34,
          type = "spike"
        },
        {
          id = 35,
          type = "redDemony"
        },
        {
          id = 36,
          type = "player"
        },
        {
          id = 39,
          type = "redButton"
        },
        {
          id = 42,
          type = "blueDemony"
        },
        {
          id = 46,
          type = "greenButton"
        },
        {
          id = 48,
          type = "endLevel"
        },
        {
          id = 53,
          type = "blueButton"
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 30,
      id = 1,
      name = "Ground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 30,
      id = 2,
      name = "Shadows",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 13, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 6, 6, 6, 6, 6, 0,
        0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 42, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 20, 6, 6, 6, 0, 0, 7, 0, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0,
        0, 7, 0, 20, 6, 6, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 14, 0, 0, 7, 0, 0, 0, 0, 7, 0, 20, 6, 6, 6, 6, 6, 6, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 14, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 20, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 21, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 20, 6, 6, 6, 6, 6, 6, 6, 0, 13, 6, 6, 6, 21, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 13, 6, 6, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 20, 0, 14, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 0, 7, 0, 20, 6, 6, 6, 6, 21, 0, 20, 6, 6, 6, 6, 6, 6, 6, 6, 6, 21, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 30,
      id = 5,
      name = "Solid",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3,
        3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3,
        3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 0, 0, 0, 0, 0, 0, 3,
        3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 3,
        3, 0, 0, 2, 2, 2, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 0, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 2, 2, 2, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 3, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 0, 3, 0, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 0, 3, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 3, 3, 3, 3,
        3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Objects",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "",
          type = "player",
          shape = "rectangle",
          x = 448,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 384,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 416,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 448,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 480,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 512,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 480,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 416,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "redDemony",
          shape = "rectangle",
          x = 416,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "blueDemony",
          shape = "rectangle",
          x = 480,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 43,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 544,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 576,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 576,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 544,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 608,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 608,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 640,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 640,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 576,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 544,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 512,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 480,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 448,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 416,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 384,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 608,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 448,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 480,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 512,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 544,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 608,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 640,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 384,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 416,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 448,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 480,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 512,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 544,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 576,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 608,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 384,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 416,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "speeder",
          shape = "rectangle",
          x = 480,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          type = "endLevel",
          shape = "rectangle",
          x = 800,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 49,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 576,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 544,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 512,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 480,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 608,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 608,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 576,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 544,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 512,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 480,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 576,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 544,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 448,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 352,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 224,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 224,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 576,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 480,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 384,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 288,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 256,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 256,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 256,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 224,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 224,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 32,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 160,
          y = 800,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 160,
          y = 832,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 416,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 416,
          y = 800,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 384,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 384,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 416,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "life",
          shape = "rectangle",
          x = 32,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 32,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "life",
          shape = "rectangle",
          x = 192,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 32,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 672,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 544,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 800,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 800,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 768,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 768,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 800,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "",
          type = "coin",
          shape = "rectangle",
          x = 800,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
